// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEyuVMos2MCfFjH9oga_xcnnD3vQiFOOg',
    appId: '1:559186602722:web:4c2a03d94bf44352ca0cbb',
    messagingSenderId: '559186602722',
    projectId: 'buzzer-beater-9853c',
    authDomain: 'buzzer-beater-9853c.firebaseapp.com',
    storageBucket: 'buzzer-beater-9853c.appspot.com',
    measurementId: 'G-CE0VX1CCN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr7WvBQvW9U6Sm5kXXDZRy7u6cPA71ExI',
    appId: '1:559186602722:android:c0d19f9531cbb4ffca0cbb',
    messagingSenderId: '559186602722',
    projectId: 'buzzer-beater-9853c',
    storageBucket: 'buzzer-beater-9853c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Z6Hts8s1rUH6WBwTdooBIpp7M1Von4U',
    appId: '1:559186602722:ios:7ad087e27d02ac65ca0cbb',
    messagingSenderId: '559186602722',
    projectId: 'buzzer-beater-9853c',
    storageBucket: 'buzzer-beater-9853c.appspot.com',
    iosBundleId: 'com.woodyvillage.buzzerbeater.buzzerBeater',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7Z6Hts8s1rUH6WBwTdooBIpp7M1Von4U',
    appId: '1:559186602722:ios:ac5ad29d1443f377ca0cbb',
    messagingSenderId: '559186602722',
    projectId: 'buzzer-beater-9853c',
    storageBucket: 'buzzer-beater-9853c.appspot.com',
    iosBundleId: 'com.woodyvillage.buzzerbeater.buzzerBeater.RunnerTests',
  );
}
